import type { Metadata } from "next";
import { Inter, Roboto } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import DummyHeader from '@/components/DummyHeader';
import BASE_URL from '@/utils/BASE_URL';
import Providers from '@/app/providers';
import RecoilContextProvider from '@/app/recoilContextProvider';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { GoogleTagManager, GoogleAnalytics } from '@next/third-parties/google';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';


const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
});
export const metadata: Metadata = {
  title: '바른번역',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <GoogleTagManager gtmId='GTM-PJD3MXTH' />
        <GoogleAnalytics gaId='G-EKS7JHLFSC' />
        {/* <meta
          httpEquiv='Content-Security-Policy'
          content='upgrade-insecure-requests'
        /> */}
      </head>
      <body className={roboto.className}>
        <AppRouterCacheProvider>
          <RecoilContextProvider>
            <Header />
            <DummyHeader />
            <Providers>{children}</Providers>
            <ToastContainer />
            <Footer />
          </RecoilContextProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
